#! /bin/sh
$HOME/scripts/startup.sh

yabar &

# amixer -D pulse sset Master 50%
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           5
bspc config normal_border_color "#141013"
bspc config focused_border_color "#16a085"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
